//! Secret storage: the OS keyring, never a file kotori writes.
//!
//! Two requirements shape this, and they pull in opposite directions:
//!   1. the user's password must **not** be readable in clear text on disk;
//!   2. the user must still be able to read it back *without kotori* (and
//!      without kopia) — a box only we can open would be another BitLocker.
//!
//! The OS keyring satisfies both: the platform encrypts the secret at rest, and
//! its owner can list it with standard tooling. kotori drives the platform's own
//! store rather than linking a client library, so what we write is exactly what
//! the user inspects by hand.
//!
//! **Dual-boot rules** (the user runs Linux *and* Windows against the same
//! bucket, so none of this may assume one machine's environment):
//!   * the sync password is **chosen by the user and never generated by us** —
//!     a password they never saw would make the backup depend on this app;
//!   * each OS keeps its own copy in its own keyring (Secret Service on Linux,
//!     Credential Manager on Windows); keyrings are per-install and never sync,
//!     so the user re-enters the same password once per system;
//!   * when no keyring is available the secret is held **in memory for the
//!     session only** — never written to a file;
//!   * nothing here ever touches `config.toml`.
//!
//! Only the Linux backend (Secret Service, driven through `secret-tool`) is
//! implemented; the Windows backend is part of the Windows port (AGENTS.md).

use std::collections::HashMap;
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::{Arc, Mutex};

/// Attributes identifying kotori's entries in the keyring.
pub const SERVICE: &str = "kotori";
/// Environment override pointing at the `secret-tool` binary (used by tests).
pub const TOOL_ENV: &str = "KOTORI_SECRET_TOOL";

/// One stored secret.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SecretKey {
    /// Backblaze application key id.
    B2KeyId,
    /// Backblaze application key.
    B2AppKey,
    /// Save-sync password, in the clear, so the user can always read it back.
    SyncPassword,
    /// The same password in the form rclone wants, so a sync run never has to
    /// put it on a command line.
    SyncPasswordObscured,
}

impl SecretKey {
    pub const ALL: [SecretKey; 4] = [
        Self::B2KeyId,
        Self::B2AppKey,
        Self::SyncPassword,
        Self::SyncPasswordObscured,
    ];

    /// Keyring "account" attribute; also what the user types into `secret-tool`.
    pub fn account(self) -> &'static str {
        match self {
            Self::B2KeyId => "b2-key-id",
            Self::B2AppKey => "b2-app-key",
            Self::SyncPassword => "sync-password",
            Self::SyncPasswordObscured => "sync-password-obscured",
        }
    }

    /// Human-readable label shown by keyring managers.
    pub fn label(self) -> &'static str {
        match self {
            Self::B2KeyId => "kotori: B2 key id",
            Self::B2AppKey => "kotori: B2 application key",
            Self::SyncPassword => "kotori: sync password",
            Self::SyncPasswordObscured => "kotori: sync password (rclone form)",
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum SecretError {
    #[error(
        "系统密钥环不可用：找不到 secret-tool。请安装 libsecret（Arch: libsecret）后重试；\
         不肯退化为明文保存"
    )]
    BackendMissing,
    #[error("这个平台的密钥环后端还没实现（{0}）；密码目前只能保存在内存里")]
    BackendUnsupported(&'static str),
    #[error("密钥环操作失败: {0}")]
    Command(String),
}

/// Which keyring implementation this build talks to.
pub const fn backend_name() -> &'static str {
    if cfg!(target_os = "linux") {
        "Secret Service (libsecret)"
    } else if cfg!(windows) {
        "Windows 凭据管理器（尚未实现）"
    } else {
        "未支持的系统密钥环"
    }
}

/// Where a [`Keyring`] keeps its entries.
#[derive(Debug, Clone)]
enum Backend {
    /// The platform's own store, driven through `secret-tool`.
    Tool(PathBuf),
    /// No keyring on this machine: hold the secrets for this session only.
    Memory(Arc<Mutex<HashMap<SecretKey, String>>>),
}

/// Handle to a secret store.
///
/// Normally this is the platform keyring. When the machine has none, the store
/// degrades to [`Keyring::memory`] — **memory for this session only**, never a
/// file: a credential written to disk in clear text is the one outcome the user
/// ruled out. The trade-off is honest and visible: the settings page says the
/// password has to be re-entered after a restart.
#[derive(Debug, Clone)]
pub struct Keyring {
    backend: Backend,
}

impl Keyring {
    /// Use a specific `secret-tool` binary.
    pub fn with_tool(tool: impl Into<PathBuf>) -> Self {
        Self {
            backend: Backend::Tool(tool.into()),
        }
    }

    /// A store that lives only as long as this process.
    pub fn memory() -> Self {
        Self {
            backend: Backend::Memory(Arc::new(Mutex::new(HashMap::new()))),
        }
    }

    /// Detect the system keyring, or explain what is missing.
    ///
    /// On Windows the Credential Manager backend still has to be written; the
    /// secret then lives in memory only, which is a supported (if less
    /// convenient) mode rather than a reason to write it to disk.
    pub fn system() -> Result<Self, SecretError> {
        if !cfg!(target_os = "linux") {
            return Err(SecretError::BackendUnsupported(backend_name()));
        }

        if let Some(explicit) = std::env::var_os(TOOL_ENV) {
            let path = PathBuf::from(explicit);
            if path.is_file() {
                return Ok(Self::with_tool(path));
            }
        }
        crate::util::executor::find_binary("secret-tool")
            .map(Self::with_tool)
            .ok_or(SecretError::BackendMissing)
    }

    /// The system keyring, or the session-only store when there is none.
    ///
    /// The second element of the pair is `true` when the secrets will not
    /// survive a restart, so callers can tell the user instead of pretending
    /// everything is fine.
    pub fn system_or_memory() -> (Self, bool) {
        match Self::system() {
            Ok(keyring) => (keyring, false),
            Err(error) => {
                tracing::warn!("{error}；本次会话的密码只保存在内存里");
                (Self::memory(), true)
            }
        }
    }

    /// True when secrets are held in memory and lost on restart.
    pub fn is_ephemeral(&self) -> bool {
        matches!(self.backend, Backend::Memory(_))
    }

    /// Name of the store, for the settings page.
    pub fn describe(&self) -> String {
        match &self.backend {
            Backend::Tool(tool) => format!("{} ({})", backend_name(), tool.display()),
            Backend::Memory(_) => "内存（没有系统密钥环，重启后需重新输入）".to_string(),
        }
    }

    fn run(&self, args: &[&str], stdin: Option<&str>) -> Result<std::process::Output, SecretError> {
        let Backend::Tool(tool) = &self.backend else {
            return Err(SecretError::Command("内存存储不需要外部命令".to_string()));
        };
        let mut command = Command::new(tool);
        command
            .args(args)
            .stdin(if stdin.is_some() {
                Stdio::piped()
            } else {
                Stdio::null()
            })
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());

        let mut child = command
            .spawn()
            .map_err(|e| SecretError::Command(format!("{}: {e}", tool.display())))?;

        if let Some(value) = stdin {
            let mut pipe = child
                .stdin
                .take()
                .ok_or_else(|| SecretError::Command("无法写入 secret-tool 标准输入".to_string()))?;
            pipe.write_all(value.as_bytes())
                .and_then(|_| pipe.write_all(b"\n"))
                .map_err(|e| SecretError::Command(e.to_string()))?;
        }

        child
            .wait_with_output()
            .map_err(|e| SecretError::Command(e.to_string()))
    }

    /// Read a secret. `Ok(None)` means "not stored".
    pub fn get(&self, key: SecretKey) -> Result<Option<String>, SecretError> {
        if let Backend::Memory(store) = &self.backend {
            let store = store
                .lock()
                .map_err(|_| SecretError::Command("内存存储已损坏".to_string()))?;
            return Ok(store.get(&key).cloned());
        }

        let output = self.run(
            &["lookup", "service", SERVICE, "account", key.account()],
            None,
        )?;
        if !output.status.success() {
            // secret-tool exits non-zero when the entry does not exist.
            return Ok(None);
        }
        let value = String::from_utf8_lossy(&output.stdout)
            .trim_end()
            .to_string();
        Ok(if value.is_empty() { None } else { Some(value) })
    }

    /// Store a secret, replacing any previous value.
    ///
    /// The value goes in over stdin so it never appears in `ps`.
    pub fn set(&self, key: SecretKey, value: &str) -> Result<(), SecretError> {
        if let Backend::Memory(store) = &self.backend {
            let mut store = store
                .lock()
                .map_err(|_| SecretError::Command("内存存储已损坏".to_string()))?;
            store.insert(key, value.to_string());
            return Ok(());
        }

        let label = format!("--label={}", key.label());
        let output = self.run(
            &[
                "store",
                &label,
                "service",
                SERVICE,
                "account",
                key.account(),
            ],
            Some(value),
        )?;
        if !output.status.success() {
            return Err(SecretError::Command(
                String::from_utf8_lossy(&output.stderr).trim().to_string(),
            ));
        }
        Ok(())
    }

    /// Remove a secret. Succeeds when it was not there in the first place.
    pub fn clear(&self, key: SecretKey) -> Result<(), SecretError> {
        if let Backend::Memory(store) = &self.backend {
            let mut store = store
                .lock()
                .map_err(|_| SecretError::Command("内存存储已损坏".to_string()))?;
            store.remove(&key);
            return Ok(());
        }

        let output = self.run(
            &["clear", "service", SERVICE, "account", key.account()],
            None,
        )?;
        if !output.status.success() {
            return Err(SecretError::Command(
                String::from_utf8_lossy(&output.stderr).trim().to_string(),
            ));
        }
        Ok(())
    }

    /// Which of our secrets exist. Used by the settings page.
    pub fn present(&self) -> Vec<SecretKey> {
        SecretKey::ALL
            .into_iter()
            .filter(|key| matches!(self.get(*key), Ok(Some(_))))
            .collect()
    }
}

/// The exact command a user can run to read a secret without kotori.
///
/// Kept per-platform on purpose: "how do I get my password back" must have a
/// concrete answer on every system the user boots into.
pub fn lookup_hint(key: SecretKey) -> String {
    if cfg!(target_os = "linux") {
        format!(
            "secret-tool lookup service {SERVICE} account {}",
            key.account()
        )
    } else if cfg!(windows) {
        format!(
            "在「控制面板 → 凭据管理器 → Windows 凭据」里找 {} / {}",
            SERVICE,
            key.account()
        )
    } else {
        format!("（{} 上还没有查阅方式）", backend_name())
    }
}

/// A stand-in `secret-tool` backed by a file, so tests never touch the user's
/// real keyring. Shared by the sync tests, which need one too.
#[cfg(test)]
pub(crate) mod testing {
    use super::{Keyring, SecretKey};
    use std::path::{Path, PathBuf};

    /// Argument every fake helper answers with an immediate, side-effect-free
    /// exit. Used by [`write_executable`].
    pub(crate) const WARMUP_FLAG: &str = "--kotori-warmup";

    /// Write a helper script and prove the kernel will actually run it.
    ///
    /// Writing a file and exec'ing it are each safe on their own, but tests run
    /// in parallel: another thread can fork between our write and our first
    /// exec and inherit the still-open write handle, which makes the kernel
    /// report `ETXTBSY` for that inode until the child execs. Retrying
    /// converges, because once our own write handle is closed nothing can open
    /// the file for writing again — and every fake script exits immediately on
    /// [`WARMUP_FLAG`], so the warm-up has no side effects.
    pub(crate) fn write_executable(path: &Path, body: &str) {
        use std::os::unix::fs::PermissionsExt;

        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(path, body).unwrap();
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).unwrap();

        for _ in 0..200 {
            match std::process::Command::new(path).arg(WARMUP_FLAG).output() {
                Ok(_) => return,
                Err(e) if e.raw_os_error() == Some(libc::ETXTBSY) => {
                    std::thread::sleep(std::time::Duration::from_millis(20));
                }
                Err(e) => panic!("cannot execute {}: {e}", path.display()),
            }
        }
        panic!("{} stayed busy", path.display());
    }

    pub(crate) struct FakeTool {
        dir: PathBuf,
        tool: PathBuf,
    }

    impl FakeTool {
        pub(crate) fn new(tag: &str) -> Self {
            let dir = std::env::temp_dir().join(format!(
                "kotori-secrets-{tag}-{}-{}",
                std::process::id(),
                uuid::Uuid::new_v4()
            ));
            std::fs::create_dir_all(&dir).unwrap();
            let tool = dir.join("secret-tool");

            // Mirrors the parts of secret-tool's interface kotori relies on:
            // entries are keyed by their `account` attribute, `store` reads the
            // secret from stdin, `lookup` prints it, `clear` removes it.
            let script = format!(
                r#"#!/bin/sh
[ "$1" = "{WARMUP_FLAG}" ] && exit 0
dir='{dir}'
name=''
prev=''
for a in "$@"; do
  if [ "$prev" = "account" ]; then name="$a"; fi
  prev="$a"
done
file="$dir/$name"
case "$1" in
  store) read -r v; printf '%s' "$v" > "$file" ;;
  lookup) [ -s "$file" ] && cat "$file" || exit 1 ;;
  clear) rm -f "$file" ;;
  *) exit 2 ;;
esac
"#,
                dir = dir.display()
            );
            write_executable(&tool, &script);

            Self { dir, tool }
        }

        pub(crate) fn keyring(&self) -> Keyring {
            Keyring::with_tool(&self.tool)
        }

        /// Where the fake tool keeps one account's secret.
        pub(crate) fn stored(&self, key: SecretKey) -> PathBuf {
            self.dir.join(key.account())
        }
    }

    impl Drop for FakeTool {
        fn drop(&mut self) {
            std::fs::remove_dir_all(&self.dir).ok();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::testing::FakeTool;
    use super::*;

    #[test]
    fn round_trips_a_secret_through_the_keyring() {
        let fake = FakeTool::new("roundtrip");
        let keyring = fake.keyring();

        assert_eq!(keyring.get(SecretKey::SyncPassword).unwrap(), None);

        keyring
            .set(SecretKey::SyncPassword, "hunter2 with spaces")
            .unwrap();
        assert_eq!(
            keyring.get(SecretKey::SyncPassword).unwrap(),
            Some("hunter2 with spaces".to_string()),
            "values are passed verbatim, whitespace included"
        );

        // The stored value is what the user would see with plain secret-tool.
        assert_eq!(
            std::fs::read_to_string(fake.stored(SecretKey::SyncPassword)).unwrap(),
            "hunter2 with spaces"
        );

        keyring.clear(SecretKey::SyncPassword).unwrap();
        assert_eq!(keyring.get(SecretKey::SyncPassword).unwrap(), None);
    }

    #[test]
    fn secrets_are_stored_under_distinct_accounts() {
        let fake = FakeTool::new("distinct");
        let keyring = fake.keyring();
        keyring.set(SecretKey::B2KeyId, "keyid").unwrap();
        keyring
            .set(SecretKey::SyncPasswordObscured, "obscured-blob")
            .unwrap();

        assert_eq!(
            keyring.get(SecretKey::B2KeyId).unwrap().as_deref(),
            Some("keyid")
        );
        assert_eq!(
            keyring
                .get(SecretKey::SyncPasswordObscured)
                .unwrap()
                .as_deref(),
            Some("obscured-blob")
        );
        assert_eq!(keyring.get(SecretKey::B2AppKey).unwrap(), None);

        // The two password entries are separate items, so the readable one and
        // the one rclone consumes cannot clobber each other.
        assert_ne!(
            SecretKey::SyncPassword.account(),
            SecretKey::SyncPasswordObscured.account()
        );
    }

    #[test]
    fn missing_backend_is_reported_instead_of_falling_back_to_plaintext() {
        let keyring = Keyring::with_tool("/nonexistent/secret-tool");
        let error = keyring.get(SecretKey::SyncPassword).unwrap_err();
        assert!(matches!(error, SecretError::Command(_)), "{error:?}");
    }

    #[test]
    fn lookup_hint_names_the_exact_command() {
        let hint = lookup_hint(SecretKey::SyncPassword);
        assert_eq!(
            hint,
            "secret-tool lookup service kotori account sync-password"
        );
        assert!(hint.contains(SERVICE));
    }

    #[test]
    fn system_detection_reports_what_is_on_this_machine() {
        // The real answer depends on the machine; the contract is that it either
        // yields a usable handle or a clear "no keyring here" error — never a
        // silent fallback to plaintext.
        match Keyring::system() {
            Ok(keyring) => assert!(!keyring.is_ephemeral()),
            Err(error) => {
                assert!(
                    matches!(
                        error,
                        SecretError::BackendMissing | SecretError::BackendUnsupported(_)
                    ),
                    "{error:?}"
                );
                // ...and that the caller degrades to memory rather than disk.
                let (fallback, ephemeral) = Keyring::system_or_memory();
                assert!(ephemeral && fallback.is_ephemeral());
            }
        }
    }

    #[test]
    fn a_machine_without_a_keyring_keeps_secrets_in_memory_only() {
        let keyring = Keyring::memory();
        assert!(keyring.is_ephemeral());
        assert!(keyring.get(SecretKey::SyncPassword).unwrap().is_none());

        keyring.set(SecretKey::SyncPassword, "hunter2").unwrap();
        assert_eq!(
            keyring.get(SecretKey::SyncPassword).unwrap().as_deref(),
            Some("hunter2")
        );
        assert_eq!(keyring.present(), vec![SecretKey::SyncPassword]);
        // The memory store never shells out, so it cannot leak through a file.
        assert!(keyring.run(&["lookup"], None).is_err());

        keyring.clear(SecretKey::SyncPassword).unwrap();
        assert!(keyring.present().is_empty());
        // Clearing twice is not an error, exactly like the real keyring.
        keyring.clear(SecretKey::SyncPassword).unwrap();
    }

    #[test]
    fn the_store_describes_itself_honestly() {
        assert!(Keyring::memory().describe().contains("内存"));
        let keyring = Keyring::with_tool("/usr/bin/secret-tool");
        assert!(keyring.describe().contains("/usr/bin/secret-tool"));
        assert!(!keyring.describe().contains("内存"));
    }

    #[test]
    fn every_platform_gets_a_concrete_way_to_read_the_secret_back() {
        // Requirement: the user must be able to recover the password without
        // kotori. That has to hold on whichever system they booted into.
        let hint = lookup_hint(SecretKey::SyncPassword);
        assert!(!hint.is_empty());
        assert!(
            hint.contains("secret-tool") || hint.contains("凭据管理器"),
            "{hint}"
        );
        assert_ne!(backend_name(), "");
    }
}
