//! Secret storage: the OS keyring, never a file kotori writes.
//!
//! Two requirements shape this, and they pull in opposite directions:
//!   1. the user's password must **not** be readable in clear text on disk;
//!   2. the user must still be able to read it back *without kotori* (and
//!      without kopia) — a box only we can open would be another BitLocker.
//!
//! The OS keyring satisfies both: the platform encrypts the secret at rest, and
//! its owner can list it with standard tooling. kotori drives the platform's own
//! store rather than linking a client library, so what we write is exactly what
//! the user inspects by hand.
//!
//! **Dual-boot rules** (the user runs Linux *and* Windows against the same
//! bucket, so none of this may assume one machine's environment):
//!   * the sync password is **chosen by the user and never generated by us** —
//!     a password they never saw would make the backup depend on this app;
//!   * each OS keeps its own copy in its own keyring (Secret Service on Linux,
//!     Credential Manager on Windows); keyrings are per-install and never sync,
//!     so the user re-enters the same password once per system;
//!   * when no keyring is available the secret is held **in memory for the
//!     session only** — never written to a file;
//!   * nothing here ever touches `config.toml`.
//!
//! Only the Linux backend (Secret Service, driven through `secret-tool`) is
//! implemented; the Windows backend is part of the Windows port (AGENTS.md).

use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};

/// Attributes identifying kotori's entries in the keyring.
pub const SERVICE: &str = "kotori";
/// Environment override pointing at the `secret-tool` binary (used by tests).
pub const TOOL_ENV: &str = "KOTORI_SECRET_TOOL";

/// One stored secret.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SecretKey {
    /// Backblaze application key id.
    B2KeyId,
    /// Backblaze application key.
    B2AppKey,
    /// Save-sync password, in the clear, so the user can always read it back.
    SyncPassword,
    /// The same password in the form rclone wants, so a sync run never has to
    /// put it on a command line.
    SyncPasswordObscured,
}

impl SecretKey {
    pub const ALL: [SecretKey; 4] = [
        Self::B2KeyId,
        Self::B2AppKey,
        Self::SyncPassword,
        Self::SyncPasswordObscured,
    ];

    /// Keyring "account" attribute; also what the user types into `secret-tool`.
    pub fn account(self) -> &'static str {
        match self {
            Self::B2KeyId => "b2-key-id",
            Self::B2AppKey => "b2-app-key",
            Self::SyncPassword => "sync-password",
            Self::SyncPasswordObscured => "sync-password-obscured",
        }
    }

    /// Human-readable label shown by keyring managers.
    pub fn label(self) -> &'static str {
        match self {
            Self::B2KeyId => "kotori: B2 key id",
            Self::B2AppKey => "kotori: B2 application key",
            Self::SyncPassword => "kotori: sync password",
            Self::SyncPasswordObscured => "kotori: sync password (rclone form)",
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum SecretError {
    #[error(
        "系统密钥环不可用：找不到 secret-tool。请安装 libsecret（Arch: libsecret）后重试；\
         不肯退化为明文保存"
    )]
    BackendMissing,
    #[error("这个平台的密钥环后端还没实现（{0}）；密码目前只能保存在内存里")]
    BackendUnsupported(&'static str),
    #[error("密钥环操作失败: {0}")]
    Command(String),
}

/// Which keyring implementation this build talks to.
pub const fn backend_name() -> &'static str {
    if cfg!(target_os = "linux") {
        "Secret Service (libsecret)"
    } else if cfg!(windows) {
        "Windows 凭据管理器（尚未实现）"
    } else {
        "未支持的系统密钥环"
    }
}

/// Handle to the platform keyring.
#[derive(Debug, Clone)]
pub struct Keyring {
    tool: PathBuf,
}

impl Keyring {
    /// Use a specific `secret-tool` binary.
    pub fn with_tool(tool: impl Into<PathBuf>) -> Self {
        Self { tool: tool.into() }
    }

    /// Detect the system keyring, or explain what is missing.
    ///
    /// On Windows the Credential Manager backend still has to be written; the
    /// secret then lives in memory only, which is a supported (if less
    /// convenient) mode rather than a reason to write it to disk.
    pub fn system() -> Result<Self, SecretError> {
        if !cfg!(target_os = "linux") {
            return Err(SecretError::BackendUnsupported(backend_name()));
        }

        if let Some(explicit) = std::env::var_os(TOOL_ENV) {
            let path = PathBuf::from(explicit);
            if path.is_file() {
                return Ok(Self::with_tool(path));
            }
        }
        crate::util::executor::find_binary("secret-tool")
            .map(Self::with_tool)
            .ok_or(SecretError::BackendMissing)
    }

    /// Is a keyring usable right now?
    pub fn available() -> bool {
        Self::system().is_ok()
    }

    fn run(&self, args: &[&str], stdin: Option<&str>) -> Result<std::process::Output, SecretError> {
        let mut command = Command::new(&self.tool);
        command
            .args(args)
            .stdin(if stdin.is_some() {
                Stdio::piped()
            } else {
                Stdio::null()
            })
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());

        let mut child = command
            .spawn()
            .map_err(|e| SecretError::Command(format!("{}: {e}", self.tool.display())))?;

        if let Some(value) = stdin {
            let mut pipe = child
                .stdin
                .take()
                .ok_or_else(|| SecretError::Command("无法写入 secret-tool 标准输入".to_string()))?;
            pipe.write_all(value.as_bytes())
                .and_then(|_| pipe.write_all(b"\n"))
                .map_err(|e| SecretError::Command(e.to_string()))?;
        }

        child
            .wait_with_output()
            .map_err(|e| SecretError::Command(e.to_string()))
    }

    /// Read a secret. `Ok(None)` means "not stored".
    pub fn get(&self, key: SecretKey) -> Result<Option<String>, SecretError> {
        let output = self.run(
            &["lookup", "service", SERVICE, "account", key.account()],
            None,
        )?;
        if !output.status.success() {
            // secret-tool exits non-zero when the entry does not exist.
            return Ok(None);
        }
        let value = String::from_utf8_lossy(&output.stdout)
            .trim_end()
            .to_string();
        Ok(if value.is_empty() { None } else { Some(value) })
    }

    /// Store a secret, replacing any previous value.
    ///
    /// The value goes in over stdin so it never appears in `ps`.
    pub fn set(&self, key: SecretKey, value: &str) -> Result<(), SecretError> {
        let label = format!("--label={}", key.label());
        let output = self.run(
            &[
                "store",
                &label,
                "service",
                SERVICE,
                "account",
                key.account(),
            ],
            Some(value),
        )?;
        if !output.status.success() {
            return Err(SecretError::Command(
                String::from_utf8_lossy(&output.stderr).trim().to_string(),
            ));
        }
        Ok(())
    }

    /// Remove a secret. Succeeds when it was not there in the first place.
    pub fn clear(&self, key: SecretKey) -> Result<(), SecretError> {
        let output = self.run(
            &["clear", "service", SERVICE, "account", key.account()],
            None,
        )?;
        if !output.status.success() {
            return Err(SecretError::Command(
                String::from_utf8_lossy(&output.stderr).trim().to_string(),
            ));
        }
        Ok(())
    }

    /// Which of our secrets exist. Used by the settings page.
    pub fn present(&self) -> Vec<SecretKey> {
        SecretKey::ALL
            .into_iter()
            .filter(|key| matches!(self.get(*key), Ok(Some(_))))
            .collect()
    }
}

/// The exact command a user can run to read a secret without kotori.
///
/// Kept per-platform on purpose: "how do I get my password back" must have a
/// concrete answer on every system the user boots into.
pub fn lookup_hint(key: SecretKey) -> String {
    if cfg!(target_os = "linux") {
        format!(
            "secret-tool lookup service {SERVICE} account {}",
            key.account()
        )
    } else if cfg!(windows) {
        format!(
            "在「控制面板 → 凭据管理器 → Windows 凭据」里找 {} / {}",
            SERVICE,
            key.account()
        )
    } else {
        format!("（{} 上还没有查阅方式）", backend_name())
    }
}

/// A stand-in `secret-tool` backed by a file, so tests never touch the user's
/// real keyring. Shared by the sync tests, which need one too.
#[cfg(test)]
pub(crate) mod testing {
    use super::{Keyring, SecretKey};
    use std::path::PathBuf;

    pub(crate) struct FakeTool {
        dir: PathBuf,
        tool: PathBuf,
    }

    impl FakeTool {
        pub(crate) fn new(tag: &str) -> Self {
            let dir = std::env::temp_dir().join(format!(
                "kotori-secrets-{tag}-{}-{}",
                std::process::id(),
                uuid::Uuid::new_v4()
            ));
            std::fs::create_dir_all(&dir).unwrap();
            let tool = dir.join("secret-tool");

            // Mirrors the parts of secret-tool's interface kotori relies on:
            // entries are keyed by their `account` attribute, `store` reads the
            // secret from stdin, `lookup` prints it, `clear` removes it.
            let script = format!(
                r#"#!/bin/sh
dir='{dir}'
name=''
prev=''
for a in "$@"; do
  if [ "$prev" = "account" ]; then name="$a"; fi
  prev="$a"
done
file="$dir/$name"
case "$1" in
  store) read -r v; printf '%s' "$v" > "$file" ;;
  lookup) [ -s "$file" ] && cat "$file" || exit 1 ;;
  clear) rm -f "$file" ;;
  *) exit 2 ;;
esac
"#,
                dir = dir.display()
            );
            std::fs::write(&tool, script).unwrap();
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                std::fs::set_permissions(&tool, std::fs::Permissions::from_mode(0o755)).unwrap();
            }

            Self { dir, tool }
        }

        pub(crate) fn keyring(&self) -> Keyring {
            Keyring::with_tool(&self.tool)
        }

        /// Where the fake tool keeps one account's secret.
        pub(crate) fn stored(&self, key: SecretKey) -> PathBuf {
            self.dir.join(key.account())
        }
    }

    impl Drop for FakeTool {
        fn drop(&mut self) {
            std::fs::remove_dir_all(&self.dir).ok();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::testing::FakeTool;
    use super::*;

    #[test]
    fn round_trips_a_secret_through_the_keyring() {
        let fake = FakeTool::new("roundtrip");
        let keyring = fake.keyring();

        assert_eq!(keyring.get(SecretKey::SyncPassword).unwrap(), None);

        keyring
            .set(SecretKey::SyncPassword, "hunter2 with spaces")
            .unwrap();
        assert_eq!(
            keyring.get(SecretKey::SyncPassword).unwrap(),
            Some("hunter2 with spaces".to_string()),
            "values are passed verbatim, whitespace included"
        );

        // The stored value is what the user would see with plain secret-tool.
        assert_eq!(
            std::fs::read_to_string(fake.stored(SecretKey::SyncPassword)).unwrap(),
            "hunter2 with spaces"
        );

        keyring.clear(SecretKey::SyncPassword).unwrap();
        assert_eq!(keyring.get(SecretKey::SyncPassword).unwrap(), None);
    }

    #[test]
    fn secrets_are_stored_under_distinct_accounts() {
        let fake = FakeTool::new("distinct");
        let keyring = fake.keyring();
        keyring.set(SecretKey::B2KeyId, "keyid").unwrap();
        keyring
            .set(SecretKey::SyncPasswordObscured, "obscured-blob")
            .unwrap();

        assert_eq!(
            keyring.get(SecretKey::B2KeyId).unwrap().as_deref(),
            Some("keyid")
        );
        assert_eq!(
            keyring
                .get(SecretKey::SyncPasswordObscured)
                .unwrap()
                .as_deref(),
            Some("obscured-blob")
        );
        assert_eq!(keyring.get(SecretKey::B2AppKey).unwrap(), None);

        // The two password entries are separate items, so the readable one and
        // the one rclone consumes cannot clobber each other.
        assert_ne!(
            SecretKey::SyncPassword.account(),
            SecretKey::SyncPasswordObscured.account()
        );
    }

    #[test]
    fn missing_backend_is_reported_instead_of_falling_back_to_plaintext() {
        let keyring = Keyring::with_tool("/nonexistent/secret-tool");
        let error = keyring.get(SecretKey::SyncPassword).unwrap_err();
        assert!(matches!(error, SecretError::Command(_)), "{error:?}");
    }

    #[test]
    fn lookup_hint_names_the_exact_command() {
        let hint = lookup_hint(SecretKey::SyncPassword);
        assert_eq!(
            hint,
            "secret-tool lookup service kotori account sync-password"
        );
        assert!(hint.contains(SERVICE));
    }

    #[test]
    fn system_detection_reports_what_is_on_this_machine() {
        // The real answer depends on the machine; the contract is that it either
        // yields a usable handle or a clear "no keyring here" error — never a
        // silent fallback to plaintext.
        match Keyring::system() {
            Ok(keyring) => assert!(keyring.tool.is_file()),
            Err(error) => assert!(
                matches!(
                    error,
                    SecretError::BackendMissing | SecretError::BackendUnsupported(_)
                ),
                "{error:?}"
            ),
        }
    }

    #[test]
    fn every_platform_gets_a_concrete_way_to_read_the_secret_back() {
        // Requirement: the user must be able to recover the password without
        // kotori. That has to hold on whichever system they booted into.
        let hint = lookup_hint(SecretKey::SyncPassword);
        assert!(!hint.is_empty());
        assert!(
            hint.contains("secret-tool") || hint.contains("凭据管理器"),
            "{hint}"
        );
        assert_ne!(backend_name(), "");
    }
}
